
-- CRIA A TABELA DE MATERIAL E SEUS TIPOS DE DADOS
CREATE TABLE	TP_MATERIAL
(
	CD_EMPRESA		INT		NOT NULL
,	CD_TP_MATERIAL	INT		NOT NULL
,	DS_TP_MATERIAL	INT		NOT NULL


	CONSTRAINT	PK_TB_TP_MATERIAL_CD_EMPRESA_CD_TP_MATERIAL	PRIMARY KEY (CD_EMPRESA, CD_TP_MATERIAL)
,	CONSTRAINT	FK_TB_TP_MATERIAL_CD_EMRPESA				FOREIGN KEY (CD_EMPRESA) REFERENCES EMPRESAS(CD_EMPRESA)
)

-- Alterando o tipo de dado de INT para VARCHAR na coluna de DS_TP_MATERIAL
--ALTER TABLE TP_MATERIAL	ALTER COLUMN DS_TP_MATERIAL VARCHAR(20) NOT NULL 