

-- CRIA A TABELA ORDEM DE PRODUCAO

CREATE TABLE ORDEM_PRODUCAO
(
	CD_EMPRESA				INT				NOT NULL
,	ID_ORDEM_PRODUCAO		INT IDENTITY	NOT NULL
,	CD_MATERIAL_PRODUCAO	INT				NOT NULL
,	QTD_PLANEJADA			DECIMAL (10,2)	NOT NULL
,	QTD_PRODUZIDA			DECIMAL (10,2)	NOT NULL
,	DT_INICIO				DATE
,	DT_FIM					DATE
,	DS_SITUACAO				CHAR(1)			CONSTRAINT CK_TB_ORDEM_PRODUCAO_SITUACAO CHECK (DS_SITUACAO IN ('A','P','F')) --(A) ABERTA, (P) PLANEJADA, (F)- FECHADA


	CONSTRAINT PK_TB_ORDEM_PRODUCAO_CD_EMPRESA_ID_ORDEM_PRODUCAO	PRIMARY KEY (CD_EMPRESA, ID_ORDEM_PRODUCAO)
,	CONSTRAINT FK_TB_ORDEM_PRODUCAO_CD_EMPRESA_CD_MATERIAL_PRODUCAO FOREIGN KEY (CD_EMPRESA, CD_MATERIAL_PRODUCAO)
				REFERENCES MATERIAL (CD_EMPRESA, CD_MATERIAL)
)