
USE MINIERP

-- CRIAÇÃO DA TABELA DE FICHA TÉCNICA

CREATE TABLE	FICHA_TECNICA
(
	CD_EMPRESA				INT				NOT NULL
,	ID_REFERENCIA			INT	 IDENTITY	NOT NULL
,	CD_MATERIAL_PRODUCAO	INT				NOT NULL
,	CD_MATERIAL_NECESSARIO	INT				NOT NULL
,	QTD_NECESSARIA			INT				NOT NULL


	CONSTRAINT PK_TB_FICHA_TECNICA_ID_REFERENCIA PRIMARY KEY (ID_REFERENCIA)
,	CONSTRAINT FK_TB_FICHA_TECNICA_CD_EMPRESA_CD_MATERIAL_PRODUCAO FOREIGN KEY (CD_EMPRESA, CD_MATERIAL_PRODUCAO) REFERENCES MATERIAL (CD_EMPRESA, CD_MATERIAL)
,	CONSTRAINT FK_TB_FICHA_TECNICA_CD_EMPRESA_CD_MATERIAL_NECESSARIO FOREIGN KEY (CD_EMPRESA, CD_MATERIAL_NECESSARIO) REFERENCES MATERIAL(CD_EMPRESA, CD_MATERIAL)
)