
-- CRIA A TABELA FORNECEDORES E SEUS TIPOS DE DADOS

CREATE TABLE FORNECEDORES
(
	CD_EMPRESA				INT				NOT NULL
,	ID_FORNECEDOR			INT	IDENTITY	NOT NULL
,	NM_RAZAO_FORNECEDOR		VARCHAR(100)	NOT NULL
,	NM_FANTASIA_FORNECEDOR	VARCHAR(30)		NOT NULL
,	DS_ENDERECO				VARCHAR(50)		NOT NULL
,	NO_ENDERECO				VARCHAR(10)		NOT NULL
,	DS_BAIRRO				VARCHAR(20)		NOT NULL
,	CD_CIDADE				VARCHAR(10)		NOT NULL
,	NO_CEP					CHAR(8)			NOT NULL
,	NO_CPF_CNPJ				VARCHAR(15)		NOT NULL
,	TP_FORNECEDOR			NCHAR(1)		CONSTRAINT CK_TF1	CHECK (TP_FORNECEDOR IN ('F', 'J'))
,	DT_CADASTRO				DATETIME		NOT NULL
,	CD_PAGAMENTO			INT	


	CONSTRAINT	PK_TB_FORNECEDOR_CD_EMPRESA_ID_FORNECEDOR	PRIMARY KEY(CD_EMPRESA, ID_FORNECEDOR)
,	CONSTRAINT	FK_TB_FORNECEDOR_CD_CIDADE					FOREIGN KEY(CD_CIDADE) REFERENCES 	CIDADES (CD_CIDADE)
,	CONSTRAINT	FK_TB_FORNECEDOR_CD_EMPRESA					FOREIGN KEY(CD_EMPRESA) REFERENCES  EMPRESAS (CD_EMPRESA)	

)